### ISSUE TITLE
Can we make `__future__.annotations` optional

### ISSUE THREAD

**Issue by marcvs** [KIT-SCC/AarcEntitlement#3]
This line fails on `python < 3.7`:
https://github.com/KIT-SCC/AarcEntitlement/blob/master/aarc_entitlement/__init__.py#L11

Commenting the line did not affect functionality (at first sight)

**Comment by lburgey** [comment]
Since the 23.12.2021, python 3.6 no longer receives security updates. I'd
rather not encourage people to use it.

**Comment by msalle** [comment]
Hi,
that is true for the upstream python, but it is still the default python(3) for e.g. RHEL/CentOS/Rocky 8 and OpenSUSE LEAP 15.3/SLES15 and they are certainly providing security updates for it. Since a large part of the distributed infrastructure is running either of those distribs, I think it would be good to support it, especially since it seems to have no impact on the code?
